default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  host: <%= ENV['DATA_DB_HOST'] %>
  username: <%= ENV['DATA_DB_USER'] %>
  password: <%= ENV['DATA_DB_PASS'] %>

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/dev.sqlite3

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>